=== AlphaDevTeam/jPOS-1/jpos/src/config/qsp/qsp-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id$ -->

<!ELEMENT qsp-config (logger*,mux*,task*,daily-task*,server*,
                      control-panel*,sequencer*,card-agent*,channel*,
		      persistent-engine*, connection-pool*, dir-poll*,
                      property*)*>
<!ATTLIST qsp-config logger IDREF #IMPLIED>
<!ATTLIST qsp-config realm  CDATA #IMPLIED>
<!ATTLIST qsp-config reload CDATA #IMPLIED>
<!ATTLIST qsp-config name   CDATA #IMPLIED>

<!-- logger -->
<!ELEMENT logger (log-listener*)>
<!ATTLIST logger name ID #REQUIRED>

<!-- log-listener -->
<!ELEMENT log-listener (property*)>
<!ATTLIST log-listener class NMTOKEN #REQUIRED>
<!ATTLIST log-listener name  CDATA #IMPLIED>

<!-- channel -->
<!ELEMENT channel (property*, filter*)*>
<!ATTLIST channel name ID #REQUIRED>
<!ATTLIST channel class NMTOKEN #REQUIRED>
<!ATTLIST channel connect (yes|no) 'no'>
<!ATTLIST channel logger IDREF #IMPLIED>
<!ATTLIST channel realm CDATA #IMPLIED>
<!ATTLIST channel header CDATA #IMPLIED>
<!ATTLIST channel packager CDATA #IMPLIED>
<!ATTLIST channel panel IDREF #IMPLIED>
<!ATTLIST channel type (client|server) #IMPLIED>
<!ATTLIST channel timeout CDATA #IMPLIED>
<!ATTLIST channel packager-config CDATA #IMPLIED>
<!ATTLIST channel packager-logger CDATA #IMPLIED>
<!ATTLIST channel packager-realm  CDATA #IMPLIED>
<!ATTLIST channel socket-factory  CDATA #IMPLIED>

<!-- filter -->
<!ELEMENT filter (property)*>
<!ATTLIST filter class NMTOKEN #REQUIRED>
<!ATTLIST filter direction (incoming|outgoing|both) 'both'>

<!-- mux -->
<!ELEMENT mux (property*,channel,request-listener*)*>
<!ATTLIST mux name ID #REQUIRED>
<!ATTLIST mux logger IDREF #IMPLIED>
<!ATTLIST mux realm CDATA #IMPLIED>
<!ATTLIST mux connect (yes|no) 'yes'>

<!-- task -->
<!ELEMENT task (property)*>
<!ATTLIST task class NMTOKEN #REQUIRED>
<!ATTLIST task logger IDREF #IMPLIED>
<!ATTLIST task realm CDATA #IMPLIED>
<!ATTLIST task name ID #IMPLIED>
<!ATTLIST task connection-pool IDREF #IMPLIED>

<!-- property -->
<!ELEMENT property EMPTY>
<!ATTLIST property name  CDATA #IMPLIED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST property file  CDATA #IMPLIED>

<!-- request-listener -->
<!ELEMENT request-listener (property)*>
<!ATTLIST request-listener class NMTOKEN #REQUIRED>
<!ATTLIST request-listener logger IDREF #IMPLIED>
<!ATTLIST request-listener realm CDATA #IMPLIED>

<!-- server  -->
<!ELEMENT server (channel,request-listener*)*>
<!ATTLIST server name ID #REQUIRED>
<!ATTLIST server port CDATA #REQUIRED>
<!ATTLIST server logger IDREF #IMPLIED>
<!ATTLIST server realm CDATA #IMPLIED>
<!ATTLIST server maxSessions CDATA #IMPLIED>
<!ATTLIST server panel IDREF #IMPLIED>

<!-- control-panel -->
<!ELEMENT control-panel (panel)*>
<!ATTLIST control-panel rows CDATA #REQUIRED>
<!ATTLIST control-panel cols CDATA #REQUIRED>

<!-- panel -->
<!ELEMENT panel EMPTY>
<!ATTLIST panel name ID #REQUIRED>

<!-- sequencer -->
<!ELEMENT sequencer (property)*>
<!ATTLIST sequencer name ID #REQUIRED>
<!ATTLIST sequencer class NMTOKEN #REQUIRED>
<!ATTLIST sequencer logger IDREF #IMPLIED>
<!ATTLIST sequencer realm CDATA #IMPLIED>

<!-- card-agent -->
<!ELEMENT card-agent (property)*>
<!ATTLIST card-agent class NMTOKEN #REQUIRED>
<!ATTLIST card-agent logger IDREF #IMPLIED>
<!ATTLIST card-agent realm CDATA #IMPLIED>
<!ATTLIST card-agent persistent-engine CDATA #IMPLIED>

<!-- persistent-engine -->
<!ELEMENT persistent-engine (property)*>
<!ATTLIST persistent-engine name ID #REQUIRED>
<!ATTLIST persistent-engine logger IDREF #IMPLIED>
<!ATTLIST persistent-engine realm CDATA #IMPLIED>

<!-- connection-pool -->
<!ELEMENT connection-pool (property)*>
<!ATTLIST connection-pool name ID #REQUIRED>
<!ATTLIST connection-pool logger IDREF #IMPLIED>
<!ATTLIST connection-pool realm CDATA #IMPLIED>

<!-- directory-poll -->
<!ELEMENT dir-poll (property)*>
<!ATTLIST dir-poll name ID #IMPLIED>
<!ATTLIST dir-poll path CDATA #REQUIRED>
<!ATTLIST dir-poll create (yes|no) 'no'>
<!ATTLIST dir-poll poolsize CDATA #IMPLIED>
<!ATTLIST dir-poll interval CDATA #IMPLIED>
<!ATTLIST dir-poll priorities CDATA #IMPLIED>
<!ATTLIST dir-poll processor CDATA #REQUIRED>
<!ATTLIST dir-poll logger IDREF #IMPLIED>
<!ATTLIST dir-poll realm  CDATA #IMPLIED>

<!-- daily-task -->
<!ELEMENT daily-task (property)*>
<!ATTLIST daily-task class NMTOKEN #REQUIRED>
<!ATTLIST daily-task logger IDREF #IMPLIED>
<!ATTLIST daily-task realm CDATA #IMPLIED>
<!ATTLIST daily-task name ID #IMPLIED>
<!ATTLIST daily-task start CDATA #REQUIRED>
<!ATTLIST daily-task poolsize CDATA #IMPLIED>

=== AlphaDevTeam/jPOS-1/jpos/src/ext/org/jpos/apps/qsp/qsp-config.xml
<?xml version="1.0" ?>
<!DOCTYPE qsp-config SYSTEM "qsp-config.dtd"> 
<qsp-config>
 <logger name="qsp">
    <log-listener name="simple" type="simple" />
    <!-- log-listener name="rotate" type="rotate" 
         filename="/tmp/qsp.log" window="86400" copies="10" / -->
 </logger>

 <mux name="acme.mux" logger="qsp" realm="acme">
  <channel name="acme.channel" 
          class="org.jpos.iso.ASCIIChannel" 
          packager="org.jpos.iso.ISO87APackager"
          host="localhost" port="8000"
          logger="qsp" realm="acme"
	  connect="no" >
   <filter class="org.jpos.iso.filter.XSLTFilter" direction="outgoing">
    <property name="xsltfile" 
              value="src/ext/org/jpos/apps/qsp/msg/outgoing.xsl" />
    <property name="reread" value="yes" />
   </filter>
   <filter class="org.jpos.iso.filter.DelayFilter" direction="incoming">
    <property name="delay" value="1000" />
   </filter>
  </channel>
  <!--request-listener class="org.jpos.apps.qsp.Connector"
    logger="qsp" realm="acme.mux.request.listener">
    <property name="destination-mux" value="acme.mux" />
    <property name="timeout" value="15000" />
  </request-listener -->
 </mux>

 <task class="org.jpos.apps.qsp.task.Sender" logger="qsp" realm="acme-sender">
  <property name="mux" value="acme.mux" />
  <property name="message" value="src/ext/org/jpos/apps/qsp/msg/0800.xml" />
  <property name="wait-for-response" value="15000" />
  <property name="initial-delay" value="1000" />
  <property name="delay" value="10000" />
 </task>

</qsp-config>

=== AlphaDevTeam/jPOS-1/jpos/src/ext-examples/qsp/dummyserver/dummyserver.xml
<?xml version="1.0" ?>
<!--

    $Id: dummyserver.xml,v 1.9 2003/09/03 00:21:19 apr Exp $

   This sample configuration file will setup a

   - A logger with a simple log listener

   - An ISOServer that will listen for incoming connections on port 8000
     with an associated Connector that will forward all received messages
     to ISOMUX

   - An ISOMUX connected to a LoopbackChannel that will 'bounce' 
     all incoming messages

              ________                 ________ 
   __________|        |               |        |    _________________ 
   port _____|  ISO   |               | ISOMUX |___| LoopbackChannel |
   8000 _____| Server |   _________   |        |   |_________________|
   __________|        |__|Connector|__|        |       |
             |________|  |_________|  |________|       \ XSLT outgoing
	                                                 filter
-->

<!DOCTYPE qsp-config SYSTEM "../../../config/qsp/qsp-config.dtd"> 
<qsp-config>
 <logger name="qsp">
    <log-listener class="org.jpos.util.SimpleLogListener"/>
    <!-- log-listener class="org.jpos.util.OperatorLogListener">
     <property name="jpos.operator.from" value="jpos-logger@cs.com.uy"      />
     <property name="jpos.operator.to"             value="apr@cs.com.uy"    />
     <property name="jpos.operator.subject.prefix" value="[jPOS] "          />
     <property name="jpos.operator.tags"           value="SystemMonitor"    />
     <property name="jpos.operator.delay"          value="10000"            />
     <property name="jpos.mail.smtp.host"          value="cs.cs.com.uy"     />
    </log-listener -->
 </logger>

 <control-panel rows="1" cols="1">
  <panel name="loopback.channel" />
 </control-panel>

 <server name="server" logger="qsp" realm="server" port="8000" >
  <channel name="client-side-channel" 
          class="org.jpos.iso.channel.ASCIIChannel" 
          packager="org.jpos.iso.packager.ISO87APackager"
          type="server" logger="qsp" realm="client-side-channel">
   <filter class="org.jpos.iso.filter.MD5Filter" direction="both">
    <property name="key" value="AnyKey" />
    <property name="fields" value="0 7 11 37 41" />
   </filter>

  </channel>
  <request-listener class="org.jpos.apps.qsp.Connector"
    logger="qsp" realm="connector">
    <property name="destination-mux" value="mux" />
    <property name="timeout" value="15000" />
  </request-listener>
 </server>

 <mux name="mux" logger="qsp" realm="mux">
  <channel name="server-side-channel" 
          class="org.jpos.iso.channel.LoopbackChannel" 
          logger="qsp" realm="acme" panel="loopback.channel" >
   <filter class="org.jpos.iso.filter.XSLTFilter" direction="incoming">
    <property name="xsltfile" 
              value="src/ext-examples/qsp/dummyserver/dummy-incoming.xsl" />
    <property name="reread" value="yes" />
   </filter>
  </channel>
 </mux>
</qsp-config>
